### ISSUE TITLE
Signed flag not being respected

### ISSUE THREAD

**Issue by luismavs** [allo-media/text2num#41]
In v 2.2.1:

>>> alpha2digit('plus quatre avion', 'fr', signed=True)
         '+4 avion'
>>> alpha2digit('plus quatre avion', 'fr', signed=False)
         'plus 4 avion'
>>> alpha2digit('deux hélicoptères plus quatre avion', 'fr', signed=True)
        '2 Hélicoptères +4 avion'
>>> alpha2digit('deux Hélicoptères plus quatre avion', 'fr', signed=False)
        '2 Hélicoptères +4 avion'

Happens for other languages too, probably associated with the existence of a previous number in the segment.

**Comment by rtxm** [comment]
Well spotted!
