### ISSUE TITLE
Error using German text

### ISSUE THREAD

**Issue by Tortoise17** [allo-media/text2num#58]
Dear Friends. 

I have tried this tool. I am facing the error. 
```

alpha2digit >>  Exception: Language not supported
text2num >> KeyError: 'de'
```

I am using version 2.4.0

Can you help me with fixing this?

**Comment by Tortoise17** [comment]
Sorry problem is with PIP package. with the master branch, it is working super. !!
Thank you for great library. Great tool. Awesome.

**Comment by rtxm** [comment]
Indeed, the German support hasn't been officially released yet, it's only on master for now.
I'm glad you find this project useful, thank you!
