### ISSUE TITLE
Error with language support now

### ISSUE THREAD

**Issue by Tortoise17** [allo-media/text2num#65]
Dear Friends. 

with the current release, now I am facing this error. 

```
    text_new = alpha2digit(text, "de", ordinal_threshold=0)
  File "/user/anaconda3/envs/test/lib/python3.6/site-packages/text_to_num/transforms.py", line 84, in alpha2digit
    raise Exception("Language not supported")
Exception: Language not supported
```

May I ask why is this now?? Please if you can guide. Earlier everything was perfect.

**Comment by rtxm** [comment]
Hello !
German support has not been released yet. You still need to use master for it.
We plan to release both German and Catalan support this month.
