### ISSUE TITLE
The model is not able to convert to numbers if hyphen is not there between words

### ISSUE THREAD

**Issue by skuma307** [allo-media/text2num#78]
Hi, Can you please train your model in a way so it don't required "hyphen" between words as it throws below error for this conversion: `text2num("what's your gsat number understood seven four two four seven one three what role would you be acting at", "en")` 

The error: `ValueError: invalid literal for text2num: "what's your gsat number understood seven four two four seven one three what role would you be acting at"`

But for five hundred, it can convert easily: `text2num("five hundred", "en")`
output: 500

Let me know your thoughts on this?

**Comment by rtxm** [comment]
There are no hyphen in the example text you gave :wink: 
You are not using the right function. `text2num()` checks that the input is a interger and returns it's value. What you want is `alpha2digits` to rewrite numbers in digit form within text, as show on the  [quickstart guide](https://text2num.readthedocs.io/en/latest/quickstart.html#find-and-transcribe). You may want to pass the `relaxed=True` optional keyword parameters if hyphen are a problem.
FYI `text2num` doesn't use machine learning, it's pure algorithm.
