### ISSUE TITLE
[FR] french ordinals throwing errors

### ISSUE THREAD

**Issue by gweber2** [allo-media/text2num#84]
Hi, 

french ordinals throw errors although they are dealt with in the code, is there a mistake or am i doing something wrong?

thank you

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-3-5c7f47a234e6>](https://localhost:8080/#) in <module>
----> 1 text2num("premier", "fr")

[/usr/local/lib/python3.8/dist-packages/text_to_num/transforms.py](https://localhost:8080/#) in text2num(text, lang, relaxed)
     85         tokens = list(dropwhile(lambda x: x in language.ZERO, text.split()))
     86         if not all(num_parser.push(word, ahead) for word, ahead in look_ahead(tokens)):
---> 87             raise ValueError("invalid literal for text2num: {}".format(repr(text)))
     88 
     89     return num_parser.value

ValueError: invalid literal for text2num: 'premier'

**Comment by rtxm** [comment]
`text2num` only convert valid intergers. `Premier` is not an integer.
What you want is `alpha2digit`:
```python
>>> alpha2digit("premier", "fr", ordinal_threshold=0)
"1er"
```
